import { Montserrat } from "next/font/google";
import "./globals.css";
import { Menu } from "@/app/components/menu/menu";

//Tipografia
const monserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${monserrat.variable} antialiased`}>
        <Menu></Menu>

        {children}
      </body>
    </html>
  );
}
